title: "divs.au | Australian historical electoral division data"
description: "historical archive of Australian federal electoral divisions with interactive maps and information about electoral redistributions."
url: "https://divs.au"
baseurl: ""

markdown: kramdown
theme: jekyll-theme-primer
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .jekyll-cache
  - .jekyll-metadata

collections:
  reports:
    output: true
    permalink: /:name/
  flags:
    output: true
    permalink: /au-flags/:path/
